### ISSUE TITLE
Still having trouble with this gem

### ISSUE THREAD

**Issue by kiafaldorius** [hybridgroup/taskmapper-unfuddle#2]
Thanks for fixing up the last issue.

unfuddle.project[] doesn't work: 
    irb(main):002:0> unfuddle.project['KanbanPad']
    NoMethodError: undefined method `length' for :name:Symbol
        from /opt/local/lib/ruby/gems/1.8/gems/ticketmaster-0.0.0/lib/ticketmaster/project.rb:59:in`search'
        from /opt/local/lib/ruby/gems/1.8/gems/ticketmaster-0.0.0/lib/ticketmaster/project.rb:53:in `each'
        from /opt/local/lib/ruby/gems/1.8/gems/ticketmaster-0.0.0/lib/ticketmaster/project.rb:53:in`search'
        from /opt/local/lib/ruby/gems/1.8/gems/ticketmaster-0.0.0/lib/ticketmaster/project.rb:22:in `find'
        from /opt/local/lib/ruby/gems/1.8/gems/ticketmaster-0.0.0/lib/ticketmaster/project.rb:76:in`[]'
        from (irb):2

Doesn't return the expected project:
    irb(main):004:0> unfuddle.project.find('name' => 'KanbanPad')
    => []

Is this another 1.8 vs 1.9 thing?

**Comment by sirupsen** [comment]
Fixed

http://github.com/Sirupsen/ticketmaster/commit/3a9e79fec13197493b937216f67595d172110488

http://github.com/Sirupsen/ticketmaster-unfuddle/commit/da14ebec9383570c811a28853a5660e998ce950b
