### ISSUE TITLE
Find ticket by number

### ISSUE THREAD

**Issue by andrewvc** [hybridgroup/taskmapper-unfuddle#7]
In unfuddle tickets are identifiable by either 'number' or 'id'. The number is what you see in the web you and and is more useful. The actual IDs of the ticket objects are used more internally.

Is there an interface to search by number?

**Comment by kiafaldorius** [comment]
You should be able to get a ticket by number by using

```
project.ticket(:number => ###)
```

where project is the Ticketmaster Project instance.

Sorry it took so long to reply, I've been really busy this week.
